// <auto-generated />
using EmployeePortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeePortalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250131134348_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeePortalApi.Entities.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdProfile");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("EmployeePortalApi.Entities.Profile", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfile"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProfile");

                    b.ToTable("Profile", (string)null);

                    b.HasData(
                        new
                        {
                            IdProfile = 1,
                            Name = "Front Developer"
                        },
                        new
                        {
                            IdProfile = 2,
                            Name = "Back Developer"
                        },
                        new
                        {
                            IdProfile = 3,
                            Name = "Analyst"
                        });
                });

            modelBuilder.Entity("EmployeePortalApi.Entities.Employee", b =>
                {
                    b.HasOne("EmployeePortalApi.Entities.Profile", "ProfilesReference")
                        .WithMany("EmployeesReference")
                        .HasForeignKey("IdProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfilesReference");
                });

            modelBuilder.Entity("EmployeePortalApi.Entities.Profile", b =>
                {
                    b.Navigation("EmployeesReference");
                });
#pragma warning restore 612, 618
        }
    }
}
